### ISSUE TITLE
DMCA

### ISSUE THREAD

**Issue by Asleep123** [Begonio/turtlegames#2]
This originally belonged to 3kh0. He has already contacted you and you ignored him. Take this down. I know him and 3kh0 is threatening to sue.

**Comment by 8lat** [comment]
@Asleep123 Hi! So you are kinda stupid and slow, and I know you made this a year ago BUT, Echo doesn't own any of the games on his site. Before he threatens to sue, tell him to learn what DMCA is. Stop harassing Begonio, when you don't know what he did. Every game on Echos site is open source, and he doesn't own any of the games. To conclude, stop fucking harassing people for dumb shit like this.

**Comment by Asleep123** [comment]
yeah that’s my bad i reread that and realized what a total dumbass i was
