### ISSUE TITLE
DMCA notice

### ISSUE THREAD

**Issue by 3kh0** [Begonio/turtlegames#3]
Hello,

We have reached out to you before, if you do not take down your site, we will file DMCA, you have 48 hours.

**Comment by Asleep123** [comment]
if this man doesnt take down then hes a skid 100%

**Comment by proudparrot2** [comment]
Ong

**Comment by ThatOnePers0n** [comment]
> if this man doesnt take down then hes a skid 100%

Over a year ago he didn't, so who's saying he doesn't just ignore this

**Comment by real-kwellercat** [comment]
do it!!!!

**Comment by 3kh0** [comment]
ong

**Comment by 3kh0** [comment]
@Begonio 36

**Comment by Asleep123** [comment]
he isnt gonna respond. 31 hours

**Comment by Asleep123** [comment]
you got like 3 hours or smth

**Comment by Asleep123** [comment]
@Begonio your stupid

**Comment by real-kwellercat** [comment]
@Begonio 2 hours

**Comment by Asleep123** [comment]
@Begonio Final warning. 1 hour left.

**Comment by ghost** [comment]
yo uh my opinion doesn't matter but i would take down the site if i were you

**Comment by Asleep123** [comment]
imagine copying 3kh0 L get ready for dmca

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/220225955-9e130266-5e60-469e-b76b-81dea97d04d6.png)

done

**Comment by real-kwellercat** [comment]
# **LMAO**
Imagine getting a 
## DMCA
from
### ECHO

**Comment by Asleep123** [comment]
- [x] d
- [x] m
- [x] c
- [x] a

**Comment by 8lat** [comment]
you all don't know what a dmca is, you don't own the games dumbass, you stole them without permission

**Comment by proudparrot2** [comment]
this is a year old lmao

**Comment by S-PScripts** [comment]
_"whos the retard who did a dmca when the user hadn't committed for 3 months"_

_**oh, it's echo!**_

**Comment by 3kh0** [comment]
Days since Feb 18, 2023: 465

**Comment by real-kwellercat** [comment]
lmfao
